/*
 * Airport REST API
 * Airport Mobile Middleware
 *
 * OpenAPI spec version: v1
 * Contact: onur.yardimci@pinsoft.ist
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hititcs.dcs.domain.model;

import com.google.gson.annotations.SerializedName;

/**
 * BoardWithBarcodeRequest
 */

public class BoardWithBarcodeRequest {

  @SerializedName("barcode")
  private String barcode = null;

  @SerializedName("flightId")
  private String flightId = null;

  public BoardWithBarcodeRequest barcode(String barcode, String flightId) {
    this.barcode = barcode;
    this.flightId = flightId;
    return this;
  }

  public String getBarcode() {
    return barcode;
  }

  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  public String getFlightId() {
    return flightId;
  }

  public void setFlightId(String flightId) {
    this.flightId = flightId;
  }
}

