/*
 * Airport REST API
 * Airport Mobile Middleware
 *
 * OpenAPI spec version: v1
 * Contact: onur.yardimci@pinsoft.ist
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hititcs.dcs.domain.model;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/**
 * BoardingResponse
 */

public class BoardingResponse {

  @SerializedName("message")
  private String message = null;

  @SerializedName("flightDetail")
  private FlightDetail flightDetail;


  public BoardingResponse aircraftInfo(String message) {
    this.message = message;
    return this;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public BoardingResponse(FlightDetail flightDetail) {
    this.flightDetail = flightDetail;
  }

  public FlightDetail getFlightDetail() {
    return flightDetail;
  }

  public void setFlightDetail(FlightDetail flightDetail) {
    this.flightDetail = flightDetail;
  }
}

