/*
 * Airport REST API
 * Airport Mobile Middleware
 *
 * OpenAPI spec version: v1
 * Contact: onur.yardimci@pinsoft.ist
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hititcs.dcs.domain.model;

import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/**
 * GetFlightsOutputDto
 */

public class GetFlightsOutputDto {

  @SerializedName("flights")
  private List<FlightSummary> flights = null;

  public GetFlightsOutputDto flights(List<FlightSummary> flights) {
    this.flights = flights;
    return this;
  }

  public GetFlightsOutputDto addFlightsItem(FlightSummary flightsItem) {
    if (this.flights == null) {
      this.flights = new ArrayList<>();
    }
    this.flights.add(flightsItem);
    return this;
  }

  public List<FlightSummary> getFlights() {
    return flights;
  }

  public void setFlights(List<FlightSummary> flights) {
    this.flights = flights;
  }


}

