/*
 * Airport REST API
 * Airport Mobile Middleware
 *
 * OpenAPI spec version: v1
 * Contact: onur.yardimci@pinsoft.ist
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hititcs.dcs.domain.model;

import com.google.gson.annotations.SerializedName;

/**
 * LoginRequest
 */

public class LoginRequest {

  @SerializedName("airline")
  private String airline = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("airlineCode")
  private String airlineCode = null;

  public LoginRequest airline(String airline) {
    this.airline = airline;
    return this;
  }

  public String getAirline() {
    return airline;
  }

  public void setAirline(String airline) {
    this.airline = airline;
  }

  public LoginRequest password(String password) {
    this.password = password;
    return this;
  }

  public LoginRequest airlineCode(String airlineCode) {
    this.airlineCode = airlineCode;
    return this;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getUsername() {
    return username;
  }

  public LoginRequest username(String username) {
    this.username = username;
    return this;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getAirlineCode() {
    return airlineCode;
  }

  public void setAirlineCode(String airlineCode) {
    this.airlineCode = airlineCode;
  }
}

