/*
 * Airport REST API
 * Airport Mobile Middleware
 *
 * OpenAPI spec version: v1
 * Contact: onur.yardimci@pinsoft.ist
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hititcs.dcs.domain.model;

import com.google.gson.annotations.SerializedName;

/**
 * PortInfo
 */

public class PortInfo {

  @SerializedName("city")
  private String city = null;

  @SerializedName("gate")
  private String gate = null;

  @SerializedName("terminal")
  private String terminal = null;

  public PortInfo city(String city) {
    this.city = city;
    return this;
  }

  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public PortInfo gate(String gate) {
    this.gate = gate;
    return this;
  }

  public String getGate() {
    return gate;
  }

  public void setGate(String gate) {
    this.gate = gate;
  }

  public PortInfo terminal(String terminal) {
    this.terminal = terminal;
    return this;
  }

  public String getTerminal() {
    return terminal;
  }

  public void setTerminal(String terminal) {
    this.terminal = terminal;
  }

}

