/*
 * Airport REST API
 * Airport Mobile Middleware
 *
 * OpenAPI spec version: v1
 * Contact: onur.yardimci@pinsoft.ist
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hititcs.dcs.domain.model;

import com.google.gson.annotations.SerializedName;

/**
 * ResponseEntity
 */

public class ResponseEntity {

  @SerializedName("body")
  private Object body = null;

  @SerializedName("statusCode")
  private StatusCodeEnum statusCode = null;

  @SerializedName("statusCodeValue")
  private Integer statusCodeValue = null;

  public ResponseEntity body(Object body) {
    this.body = body;
    return this;
  }

  public Object getBody() {
    return body;
  }

  public void setBody(Object body) {
    this.body = body;
  }

  public ResponseEntity statusCode(StatusCodeEnum statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  public StatusCodeEnum getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(StatusCodeEnum statusCode) {
    this.statusCode = statusCode;
  }

  public ResponseEntity statusCodeValue(Integer statusCodeValue) {
    this.statusCodeValue = statusCodeValue;
    return this;
  }

  public Integer getStatusCodeValue() {
    return statusCodeValue;
  }

  public void setStatusCodeValue(Integer statusCodeValue) {
    this.statusCodeValue = statusCodeValue;
  }


}

