# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :android

  desc "Build debug"
    lane :build_debug do
      build_android_app(task:"clean assembleDebug")
    end
